// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xumbjozzuvzgpzzwpgpo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1bWJqb3p6dXZ6Z3B6endwZ3BvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ3ODY3MDgsImV4cCI6MjA4MDM2MjcwOH0.nUpc-zaFQO8NbhNdWIWgONFktWEiYXfTRgsoqRnlh6M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);