// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://hnpzbjsinuwanyecttnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhucHpianNpbnV3YW55ZWN0dG5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU2ODkzODksImV4cCI6MjA4MTI2NTM4OX0.Mt5dHz8t6iLmOwf00eiwretNjbTYaTp8YAYgwUZ176s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);